apiVersion: v1
entries:
  zstats:
  - apiVersion: v1
    appVersion: 1.40.0
    created: 2020-09-10T14:40:11.959565631-07:00
    description: Zebrium stats collector for Kubernetes.
    digest: a91e028bd3052bdce24b1e060b23dce12aa72ef55b978ad42ed0de145cbefba0
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - stats
    - prometheus
    - agent
    - events
    maintainers:
    - email: dara@zebrium.com
      name: dara
    name: zstats
    sources:
    - https://github.com/zebrium/ze-stats
    urls:
    - https://github.com/zebrium/ze-stats/releases/download/1.40.0/zstats-1.40.0.tgz
    version: 1.40.0
generated: 2020-09-10T14:40:11.959277883-07:00
