apiVersion: v1
entries:
  zstats:
  - apiVersion: v1
    appVersion: 1.40.1
    created: 2020-09-11T14:51:39.817205715-07:00
    description: Zebrium stats collector for Kubernetes.
    digest: de5f28f0899e967698190a9ec5e0496dad891fdef5988aca1f4b129be125c571
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - stats
    - prometheus
    - agent
    - events
    maintainers:
    - email: dara@zebrium.com
      name: dara
    name: zstats
    sources:
    - https://github.com/zebrium/ze-stats
    urls:
    - https://github.com/zebrium/ze-stats/releases/download/1.40.1/zstats-1.40.1.tgz
    version: 1.40.1
generated: 2020-09-11T14:51:39.816909078-07:00
