apiVersion: v1
entries:
  zstats:
  - apiVersion: v1
    appVersion: 1.39.0
    created: 2020-08-28T13:51:48.017625819-07:00
    description: Zebrium stats collector for Kubernetes.
    digest: 820111342e9696946f9e815a90483d4d1621bfb72a4089509355a345fa0ad849
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - stats
    - prometheus
    - agent
    - events
    maintainers:
    - email: dara@zebrium.com
      name: dara
    name: zstats
    sources:
    - https://github.com/zebrium/ze-stats
    urls:
    - https://github.com/zebrium/ze-stats/releases/download/1.39.0/zstats-1.39.0.tgz
    version: 1.39.0
generated: 2020-08-28T13:51:48.017299339-07:00
