apiVersion: v1
entries:
  zstats:
  - apiVersion: v1
    appVersion: 1.22.0
    created: "2020-02-26T18:24:57.650515469-08:00"
    description: Zebrium stats collector for Kubernetes.
    digest: 0ebac4d3fe5a3484e6b92f0363b07d78fb63984066c617d582406ea351914ebf
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - stats
    - prometheus
    - agent
    - events
    maintainers:
    - email: dara@zebrium.com
      name: dara
    name: zstats
    sources:
    - https://github.com/zebrium/ze-stats
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-stats/master/charts/zstats-1.22.0.tgz
    version: 1.22.0
generated: "2020-02-26T18:24:57.649505771-08:00"
