apiVersion: v1
entries:
  zstats:
  - apiVersion: v1
    appVersion: 1.22.0
    created: 2020-03-09T17:30:27.782223177-07:00
    description: Zebrium stats collector for Kubernetes.
    digest: ac4ec7197a2f23520ac914b871de736756174e118090d23a22efd57415369549
    home: https://www.zebrium.com
    icon: https://www.zebrium.com/hubfs/logo2.png
    keywords:
    - stats
    - prometheus
    - agent
    - events
    maintainers:
    - email: dara@zebrium.com
      name: dara
    name: zstats
    sources:
    - https://github.com/zebrium/ze-stats
    urls:
    - https://raw.githubusercontent.com/zebrium/ze-stats/master/charts/zstats-1.22.0.tgz
    version: 1.22.0
generated: 2020-03-09T17:30:27.780756375-07:00
