image:
  name: zebrium/zstats
  tag: latest
  pullPolicy: Always

prometheus:
  scrapeInterval: "60s"
  evaluationInterval: "60s"

zebrium:
  deployment: ""
  collectorUrl: ""
  authToken: ""
  autoupdate: "0"
  name: zstats-collector

resources:
  requests:
    cpu: 20m
    memory: 500Mi
  limits:
    memory: 1Gi

updateStrategy: OnDelete
