image:
  name: zebrium/zstats
  tag: latest
  pullPolicy: Always

prometheus:
  scrapeInterval: "30s"
  evaluationInterval: "60s"

nodeExporter:
  enabled: true
  port: 9101
  targetPort: 9101
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

zebrium:
  deployment: ""
  collectorUrl: ""
  authToken: ""
  autoupdate: "0"
  verifySSL: true
  name: zstats-collector

resources:
  requests:
    cpu: 20m
    memory: 500Mi
  limits:
    cpu: 1000m
    memory: 2Gi

updateStrategy: OnDelete
