image:
  name: zebrium/zstats
  tag: latest
  pullPolicy: Always

prometheus:
  scrapeInterval: "30s"
  evaluationInterval: "60s"

zebrium:
  deployment: ""
  collectorUrl: ""
  authToken: ""
  autoupdate: "1"
  verifySSL: true
  enableDebug: false
  name: zstats-collector

resources:
  requests:
    cpu: 20m
    memory: 500Mi
  limits:
    cpu: 1000m
    memory: 2Gi

updateStrategy: OnDelete
