apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "zstats-collector.fullname" . }}-server-conf
  labels:
    name: prometheus-server-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: "{{ .Values.prometheus.scrapeInterval }}"
      evaluation_interval: "{{ .Values.prometheus.evaluationInterval }}"
    scrape_configs:
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        metric_relabel_configs:
        - source_labels: [namespace]
          regex: '(kube-.+|zebrium.*|istio-system|monitoring|^$)'
          action: drop
        - source_labels: [container]
          regex: '(^$)'
          action: drop
        - source_labels: [__name__]
          regex: '(container_cpu_load.+|container_cpu_(system|usage|user)_seconds_total|container_fs_(reads?|writes?)_(seconds|bytes|total).*|container_memory_(rss|swap|usage).*|container_network_(receive|transmit).+|container_tasks_state)'
          action: keep

      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        {{- if .Values.zebrium.prometheusIoScrapeEnabled }}
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        {{- else }}
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_zebrium_io_scrape]
          action: keep
          regex: true
        {{- end }}
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: '(node_cpu_seconds_.+|node_disk_.+|node_filesystem_.+|node_memory_.+|node_vmstat_.+)'
          action: keep

      - job_name: 'custom-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        {{- if .Values.zebrium.prometheusIoScrapeEnabled }}
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        {{- else }}
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_zebrium_custom_scrape]
          action: keep
          regex: true
        {{- end }}
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
