{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: {{ template "zstats-collector.name" . }}-node-exporter
  name: {{ template "zstats-collector.fullname" . }}-node-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: {{ .Values.nodeExporter.port }}
    targetPort: {{ .Values.nodeExporter.targetPort }}
    protocol: TCP
  selector:
    app: {{ template "zstats-collector.name" . }}-node-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "zstats-collector.fullname" . }}-node-exporter
spec:
  selector:
    matchLabels:
      app: {{ template "zstats-collector.name" . }}-node-exporter
  template:
    metadata:
      labels:
        app: {{ template "zstats-collector.name" . }}-node-exporter
      name: {{ template "zstats-collector.fullname" . }}-node-exporter
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter
        args:
          - --path.procfs=/host/proc
          - --path.sysfs=/host/sys
          - --web.listen-address=0.0.0.0:{{ .Values.nodeExporter.targetPort }}
        ports:
        - name: scrape
          containerPort: {{ .Values.nodeExporter.targetPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.nodeExporter.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.nodeExporter.port }}
        resources:
{{ toYaml .Values.nodeExporter.resources | indent 12 }}
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            readOnly:  true
          - name: sys
            mountPath: /host/sys
            readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
{{- end }}
