apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "zstats-collector.fullname" . }}
  labels:
    app: {{ template "zstats-collector.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
